[book]
title = "T4n OS Documentation"
authors = ["T4n Tech"]
language = "en"
multilingual = true
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/t4n-tech/"
